#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server:

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
path_2_file=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_2_file" "$username@$server_ip:~/"
