#!/usr/bin/env bash
# This script configures an Ubuntu machine to install Nginx and set up a custom 404 page

# Update package list and install nginx
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Start nginx service
sudo service nginx start

# Allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/channel/UCp3-fAm8evf5G0PB2Z0_hzA permanent;' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart nginx to apply changes
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
