#!/usr/bin/env bash
# This script installs and configures HAProxy on a new Ubuntu machine

# It sets up HAProxy to distribute traffic to web-01 and web-02 using a round-robin algorithm

# Uncomment the next line to see each command as it runs for debugging purposes
# set -x

echo -e "Updating and doing some minor checks...\n"

# Function to install a package if it is not already installed
function install() {
    command -v "$1" &> /dev/null

    #shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${1} is already installed.\n"
    fi
}

# Install HAProxy
install haproxy

echo -e "\nSetting up some minor stuff.\n"

# Backup the default HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Create the HAProxy configuration
server_config="
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 525150-web-01 100.26.230.160:80 check
    server 525150-web-02 100.25.109.10:80 check
"

# Write the configuration to HAProxy config file
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Test HAProxy configuration for syntax errors
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
#shellcheck disable=SC2181
if [ $? -ne 0 ]; then
    echo "HAProxy configuration contains errors. Please review the configuration."
    exit 1
else
    echo "HAProxy configuration is valid."
fi

# Enable HAProxy to be managed via init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart HAProxy service to apply changes
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

echo "HAProxy has been configured to distribute traffic between web-01 and web-02 using roundrobin algorithm."
