#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend mosab
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 525150-web-01 100.26.230.160:80 check
    server 525150-web-02 100.25.109.10:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
