#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code from the Apache log file and displays the data

awk '{ count[$1" "$9]++ } END { for (key in count) print count[key], key }' apache-access.log | sort -nr
