#!/usr/bin/env bash
# Generate the RSA key pair with 4096 bits

# Define the key file name and passphrase
KEY_NAME="school"
PASSPHRASE="betty"
ssh-keygen -t rsa -b 4096 -f "$KEY_NAME" -N "$PASSPHRASE" <<< y
