#!/bin/bash
# Script to generate an RSA key pair

# Define the key file name and passphrase
KEY_NAME="school"
PASSPHRASE="betty"

# Generate the RSA key pair with 4096 bits
ssh-keygen -t rsa -b 4096 -f "$KEY_NAME" -N "$PASSPHRASE"